stages:
  - build
  - deploy

build_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker build  -f Dockerfile --build-arg INST_ARGS=--production --build-arg TIMESTAMP=$(date '+%Y%m%d%H%M%S') -t "$ECR_API_BASE_URL/qa/check/search:$CI_COMMIT_SHA"  .
    - docker push "$ECR_API_BASE_URL/qa/check/search:$CI_COMMIT_SHA"
  only:
    - develop

deploy_qa:
  image: python:3-alpine
  stage: deploy
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - pip install boto3==1.14.47
    - pip install botocore==1.17.47
    - pip install ecs-deploy==1.11.0
    - ecs deploy ecs-qa  qa-check-search --image qa-check-search $ECR_API_BASE_URL/qa/check/search:$CI_COMMIT_SHA --exclusive-env -e qa-check-search DEPLOY_ENV qa -e qa-check-search AWS_DEFAULT_REGION $AWS_DEFAULT_REGION --timeout 1800 
    - echo "new Image was deployed $ECR_API_BASE_URL/qa/check/search:$CI_COMMIT_SHA"
  only:
    - develop

build_live:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker build  -f Dockerfile --build-arg INST_ARGS=--production --build-arg TIMESTAMP=$(date '+%Y%m%d%H%M%S') -t "$ECR_API_BASE_URL/live/check/search:$CI_COMMIT_SHA"  .
    - docker push "$ECR_API_BASE_URL/live/check/search:$CI_COMMIT_SHA"
  only:
    - master

deploy_live:
  image: python:3-alpine
  stage: deploy
  when: manual
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - pip install boto3==1.14.47
    - pip install botocore==1.17.47
    - pip install ecs-deploy==1.11.0
    - ecs deploy ecs-live  live-check-search --image live-check-search $ECR_API_BASE_URL/live/check/search:$CI_COMMIT_SHA --exclusive-env -e live-check-search DEPLOY_ENV live -e live-check-search AWS_DEFAULT_REGION $AWS_DEFAULT_REGION --timeout 1800
    - echo "new Image was deployed $ECR_API_BASE_URL/live/check/search:$CI_COMMIT_SHA"
  only:
    - master
