name: Continuous Integration

on: [push]

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status}}
        fields: repo,message,commit,author,ref,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
    - name: Run ESLint
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: cp config.js.example config.js
    - run: npm run test:lint
    - run: npm test

